name: CI / "Storyteller UI" app
on:
  # Doc on issue_comment event: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
  issue_comment:
    types: [created, edited]
jobs:
  test_and_build:
    name: Test, lint and build
    if: github.event.issue.pull_request
    strategy:
      matrix:
        node: ["18"]

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup workflow variables
        id: workflow-vars
        shell: bash
        run: |
          echo "::set-output name=sha::$(echo ${GITHUB_SHA})"
          echo "::set-output name=branch::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})"

      - name: Check Github SHA
        run: |
          echo "SHA: ${{ steps.workflow-vars.outputs.sha }}"
          echo "Branch: ${{ steps.workflow-vars.outputs.branch }}"

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        if: github.event.issue.pull_request && contains(github.event.comment.body, '/coverage')
        run: npm test --coverage

      - name: Deploy for review
        if: github.event.issue.pull_request && contains(github.event.comment.body, '/review')
        run: |
          git fetch --unshallow
          git checkout deploy/review
          git pull
          git merge --no-ff --no-edit ${{ steps.workflow-vars.outputs.sha }} -m "Merge ${{ steps.workflow-vars.outputs.sha }} into deploy/review"
