name: CI / "Storyteller UI" app
on: pull_request
jobs:
  test_and_build:
    name: Test, lint and build
    strategy:
      matrix:
        node: ["18"]

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup workflow variables
        id: workflow-vars
        shell: bash
        run: |
          echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Check Github SHA
        run: |
          echo "SHA: ${{ steps.workflow-vars.outputs.sha }}"

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
